namespace: cool5000_controller_manager
diagnostics_rate: 5
serial_ports:
     ttyUSB0:
        port_name: /dev/ttyUSB0
        baud_rate: 1000000
        min_motor_id: 0
        max_motor_id: 6
        update_rate: 50
        diagnostics:
            error_level_temp: 70
            warn_level_temp: 65

